### ISSUE TITLE
can not start 'func.js' in examples dir through cli

### ISSUE THREAD

**Issue by hydra1983** [metrue/fx#515]
* OS Info

```bash
sw_vers                                                                                                                          22:07   20-04-12
ProductName:	Mac OS X
ProductVersion:	10.14.4
BuildVersion:	18E226
```

* Docker Info

```bash
docker info                                                                                                                      22:06   20-04-12
Client:
 Debug Mode: false

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 15
 Server Version: 19.03.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.76-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 5.809GiB
 Name: docker-desktop
 ID: 7DKS:ORKL:WXBH:MUU7:74MH:FO3Y:DHNB:EJ7D:IJRX:QLNG:SHFA:JDPC
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 40
  Goroutines: 55
  System Time: 2020-04-12T14:07:15.441097481Z
  EventsListeners: 3
 HTTP Proxy: gateway.docker.internal:3128
 HTTPS Proxy: gateway.docker.internal:3129
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Registry Mirrors:
 Live Restore Enabled: false
 Product License: Community Engine
```

* Working dir

```bash
ls -l                                                                                                                            22:06   20-04-12
total 92
-rw-r--r--  1 edison  3215 Apr 10 09:38 CODE_OF_CONDUCT.md
-rw-r--r--  1 edison  1087 Apr 10 09:38 LICENSE
-rw-r--r--  1 edison  1698 Apr 10 09:38 Makefile
-rw-r--r--  1 edison 11787 Apr 10 09:38 README.md
drwxr-xr-x  3 edison    96 Apr 10 09:38 assets
drwxr-xr-x  4 edison   128 Apr 10 09:38 bundle
drwxr-xr-x 14 edison   448 Apr 10 09:38 bundler
drwxr-xr-x  4 edison   128 Apr 10 09:38 config
drwxr-xr-x  4 edison   128 Apr 10 09:38 constants
drwxr-xr-x  5 edison   160 Apr 10 09:38 container_runtimes
drwxr-xr-x  5 edison   160 Apr 10 09:38 context
drwxr-xr-x  3 edison    96 Apr 10 09:38 contrib
drwxr-xr-x  3 edison    96 Apr 10 09:38 docs
drwxr-xr-x  3 edison    96 Apr 10 09:38 doctor
drwxr-xr-x  8 edison   256 Apr 10 09:38 driver
drwxr-xr-x  4 edison   128 Apr 10 09:38 examples
-rw-r--r--  1 edison  6358 Apr 10 09:38 fx.go
-rw-r--r--  1 edison  2328 Apr 10 09:38 go.mod
-rw-r--r--  1 edison 55369 Apr 10 09:38 go.sum
drwxr-xr-x  3 edison    96 Apr 10 09:38 hack
drwxr-xr-x  8 edison   256 Apr 10 09:38 handlers
drwxr-xr-x  8 edison   256 Apr 10 09:38 hook
drwxr-xr-x 12 edison   384 Apr 10 09:38 middlewares
drwxr-xr-x  8 edison   256 Apr 10 09:38 packer
drwxr-xr-x  5 edison   160 Apr 10 09:38 pkg
drwxr-xr-x  5 edison   160 Apr 10 09:38 provisioner
drwxr-xr-x  9 edison   288 Apr 10 09:38 scripts
drwxr-xr-x  7 edison   224 Apr 10 09:38 test
drwxr-xr-x  7 edison   224 Apr 10 09:38 types
drwxr-xr-x 11 edison   352 Apr 10 09:38 utils
```

* Start func.js

```bash
fx up --name hello ./examples/functions/JavaScript/func.js                                                                       22:09   20-04-12
+------------------------------------------------------------------+--------+---------------+
|                                ID                                |  NAME  |   ENDPOINT    |
+------------------------------------------------------------------+--------+---------------+
| 783f7dfaf4299d61b6b86c781f76e0c3cebbc75f36e0b790295d1bc8d76e6a8c | /hello | 0.0.0.0:58386 |
+------------------------------------------------------------------+--------+---------------+
```

* Docker containers

```bash
docker ps -a                                                                                                                     22:09   20-04-12
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                    NAMES
5d3b83c77290        bobrik/socat        "socat TCP-LISTEN:12…"   6 minutes ago       Up 6 minutes        0.0.0.0:8866->1234/tcp   fx-agent
```

* Access endpoint

```bash
curl -v 0.0.0.0:58386                                                                                                            22:12   20-04-12
* Rebuilt URL to: 0.0.0.0:58386/
*   Trying 0.0.0.0...
* TCP_NODELAY set
* Connection failed
* connect to 0.0.0.0 port 58386 failed: Connection refused
* Failed to connect to 0.0.0.0 port 58386: Connection refused
* Closing connection 0
curl: (7) Failed to connect to 0.0.0.0 port 58386: Connection refused
```

* Lookup endpoint

```bash
sudo lsof -nP -i4TCP|grep 58386
# nothing displayed
```

* Home brew info

```bash
 brew info metrue/fx/fx                                                                                                           22:20   20-04-12
metrue/fx/fx: stable 0.9.34-alpha.4527da6
fx, a simple but powerful Function as a Service build tools
https://github.com/metrue/fx
/usr/local/Cellar/fx/0.9.34-alpha.4527da6 (4 files, 36MB) *
  Built from source on 2020-04-12 at 22:05:57
From: https://github.com/metrue/homebrew-fx/blob/master/Formula/fx.rb
==> Dependencies
Required: docker ✔
==> Analytics
install: 487 (30 days), 2,936 (90 days), 10,655 (365 days)
install-on-request: 488 (30 days), 2,930 (90 days), 10,651 (365 days)
build-error: 0 (30 days)
```

* fx version

```bash
fx --version                                                                                                                     22:18   20-04-12
fx version 0.9.34
```

**Comment by metrue** [comment]
@hydra1983 

I just tested it, everything works, but I am on version 0.9.35.  would you please try, 
```
DISABLE_CONTAINER_AUTOREMOVE=true fx up --name hello ./examples/functions/JavaScript/func.js      
```

Then you can `docker logs hello` to check the logs why it could not startup.

**Comment by hydra1983** [comment]
```bash
DISABLE_CONTAINER_AUTOREMOVE=true fx up --name hello ./examples/functions/JavaScript/func.js                                     10:52   20-04-16
+------------------------------------------------------------------+--------+---------------+
|                                ID                                |  NAME  |   ENDPOINT    |
+------------------------------------------------------------------+--------+---------------+
| 195d85251eb7ff8af1204d9d1a1f88f8ffac402b9cb3734363ce6bcc1ff71c4d | /hello | 0.0.0.0:49431 |
+------------------------------------------------------------------+--------+---------------+
```

```bash
docker ps -a                                                                                                                     10:52   20-04-16
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                     PORTS                    NAMES
195d85251eb7        hello:latest        "node app.js"            6 seconds ago       Exited (1) 5 seconds ago                            hello
5d3b83c77290        bobrik/socat        "socat TCP-LISTEN:12…"   3 days ago          Up 3 days                  0.0.0.0:8866->1234/tcp   fx-agent
```

```bash
docker logs --tail 200 hello                                                                                                     10:52   20-04-16
module.js:529
    throw err;
    ^

Error: Cannot find module '@koa/cors'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/app.js:3:14)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
```

I think the dependency should be ready in the container, is it? Or I need to do more to run the example?

**Comment by metrue** [comment]
Yes,  it has been already included in base image https://github.com/metrue/fx/blob/master/assets/dockerfiles/base/node/package.json#L13

Would you help to investigate more a little, here is what you can do,

* export the generated project
```
fx image export -o hello ./examples/functions/JavaScript/func.js
```
* build it manually
```
cd hello
docker build -t hello .
```
* run it and test
```
docker run -p 3000:3000 hello
curl 127.0.0.1:3000 
```

**Comment by hydra1983** [comment]
```bash
fx image export -o hello ./examples/functions/JavaScript/func.js
```

```bash
cd hello
ls -l                                                                                                                      15:58   20-04-16
total 12
-rw-r--r-- 1 edison  70 Apr 16 15:56 Dockerfile
-rw-r--r-- 1 edison 251 Apr 16 15:56 app.js
drwxr-xr-x 3 edison  96 Apr 16 15:56 dockerfiles
-rw-r--r-- 1 edison  57 Apr 16 15:56 fx.js
```

```bash
docker build -t hello .                                                                                                    15:56   20-04-16
Sending build context to Docker daemon  86.02kB
Step 1/4 : FROM metrue/fx-node-base
 ---> 7728e7963c0c
Step 2/4 : COPY . .
 ---> e203a4159f67
Step 3/4 : EXPOSE 3000
 ---> Running in 32a24519f199
Removing intermediate container 32a24519f199
 ---> 657c203bf03f
Step 4/4 : CMD ["node", "app.js"]
 ---> Running in e64639f145af
Removing intermediate container e64639f145af
 ---> 6ff922b731cc
Successfully built 6ff922b731cc
Successfully tagged hello:latest
```

```bash
docker run -p 3000:3000 hello                                                                                              15:56   20-04-16
module.js:529
    throw err;
    ^

Error: Cannot find module '@koa/cors'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/app.js:3:14)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
```

```bash
docker images                                                                                                              15:58   20-04-16
REPOSITORY                             TAG                 IMAGE ID            CREATED              SIZE
hello                                  latest              6ff922b731cc        About a minute ago   675MB
679f0946-34b0-4a1a-946a-37065073a8d2   latest              82f6b7c7e5ca        3 days ago           675MB
e758baa4-0f40-4909-b11f-f62bf6c7a4bd   latest              82f6b7c7e5ca        3 days ago           675MB
4d7485bc-50e3-4cbd-9957-66594de1ff27   latest              d07f3d27406f        3 days ago           675MB
c8962948-2e92-406c-b3d0-de2faa5e2d8e   latest              294759f634ca        3 days ago           675MB
de92b1c8-48b1-4009-9d13-dca1b65abdcf   latest              294759f634ca        3 days ago           675MB
e03276d1-d633-4367-b6b5-a18a927b49ca   latest              294759f634ca        3 days ago           675MB
36405c5a-32c7-4cb1-8af9-ada9261f4c2e   latest              294759f634ca        3 days ago           675MB
57b5334a-8090-4306-bdbd-e2041bec10a8   latest              294759f634ca        3 days ago           675MB
73e778e4-26f0-4bc7-af0e-a90b8c7761d7   latest              294759f634ca        3 days ago           675MB
9b0d5f49-a21f-4b36-91e2-4d302fd2435e   latest              294759f634ca        3 days ago           675MB
b13e4449-3cb4-447d-805b-2ffd69131806   latest              294759f634ca        3 days ago           675MB
minio/minio                            8445-9573ea5        750e04dd2779        5 months ago         95.6MB
metrue/fx-node-base                    latest              7728e7963c0c        21 months ago        675MB
bobrik/socat                           latest              e617a56c238e        4 years ago          6.95MB
```

**Comment by metrue** [comment]
@hydra1983 

I think it's because the docker image `metrue/fx-node-base` is too old, I just check it on my host,
```
$ docker images | grep fx-node-base
metrue/fx-node-base                    latest              e3de3bfeba5f        2 months ago        941MB
```
Pulling the latest version of `metrue/fx-node-base` should fix this issue.
```
docker pull metrue/fx-node-base
```

**Comment by hydra1983** [comment]
Yes, that's the problem. Thanks you so much. :D
